"""Added activation code and time limit in Users table.

Revision ID: 74e41ad351bd
Revises: c5341aaa8485
Create Date: 2020-07-15 15:47:30.063172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e41ad351bd'
down_revision = 'c5341aaa8485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_code', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('activation_timelimit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activation_timelimit')
        batch_op.drop_column('activation_code')

    # ### end Alembic commands ###
